---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-deploy
  labels:
    app: facebook

spec:
  selector:
    matchLabels:
      app: facebook
  replicas: 3
  template:
    metadata:
      name: fb-pod
      labels:
        app: facebook
  
      
    spec:
      containers:
        - name: fb-deploy-cont
          image: devopshubg333/batch16d:pythonimg
          ports:
            - containerPort: 80
